### ISSUE TITLE
Load she wasm from different location

### ISSUE THREAD

**Issue by Moumouls** [herumi/she-wasm#8]
Hi @herumi,

I encountered some difficulties when i tried to load the she-wasm file (browser side) from a specific location.

Ex: app is served over `http://awebsite.com/xxxx/home` and she wasm is served on `htpp://awebsite.com/asset-xxx/she_wasm.wasm`

In an old version i tried to unpack the auto generated JS code and then add so custom logic. But it seems not suitable for further updates.

Do you have an advice on how to specify a custom URL for the she_wasm file ?

**Comment by herumi** [comment]
I'm sorry to lack of description.
The latest version does not require she.wasm. You include only she.js.
Please see https://github.com/herumi/she-wasm#how-to-use
